# Crie um arquivo chamado dados.py que insira ao menos 5 linhas em cada tabela, e 10 linhas na tabela de vendas. 
# Na tabela de histórico de preços, coloque o preço atual e a data atual de cada produto criado. 

# Procure inserir informações de forma que as consultas a seguir retornem algum resultado.

# Crie um arquivo chamado consultas.py que responda às consultas a seguir:
# 1 - Liste todo o histórico de preços (valor, data) do produto "Caneta Bic esferográfica azul".

# 2 - Liste descrição e preço de todos os produtos da categoria "Papelaria", ordenados no menor para o maior preço.
# 3 - Recupere os nomes dos clientes que fizeram ao menos uma compra com valor superior a R$ 5.000,00 no mês de setembro/2022. Exiba-os em ordem alfabética.



from esquema import CATEGORIA, CLIENTE, PRODUTOS, HISTORICO_PRECOS, VENDAS


categorias = [
    {'descricao' : "Papelaria"},
    {'descricao' : "Higiene"},
    {'descricao' : "Informatica"},
    {'descricao' : "Padaria"},
    {'descricao' : "Bebidas"}
]

CATEGORIA.insert_many(categorias).execute()

clientes = [
    {'nome' : "Edgler Martins", 'endereco' : "Rua 1, Nº 1, Bairro 1"},
    {'nome' : "Helder Martins", 'endereco' : "Rua 2, Nº 2, Bairro 2"},
    {'nome' : "Maria dos Remedios", 'endereco' : "Rua 3, Nº 3, Bairro 3"},
    {'nome' : "Eveline Martins", 'endereco' : "Rua 4, Nº 4, Bairro 4"},
    {'nome' : "Paulo Martins", 'endereco' : "Rua 5, Nº 5, Bairro 5"}
]

CLIENTE.insert_many(clientes).execute()

produtos = [
    {'descricao' :  "Caneta Bic esferográfica azul", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Papelaria") , 'valor' : 1.30},
    {'descricao' :  "Folha A4 - 500 unidades", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Papelaria") , 'valor' : 28},
    {'descricao' :  "Tesoura", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Papelaria") , 'valor' : 5.30},
    {'descricao' :  "Grampeador", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Papelaria") , 'valor' : 25.60},
    {'descricao' :  "Regua 30cm", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Papelaria") , 'valor' : 3},
    {'descricao' :  "Papel Higienico 16 unidade", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Higiene") , 'valor' : 18.80},
    {'descricao' :  "Creme Dental", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Higiene") , 'valor' : 2.50},
    {'descricao' :  "Lamina de Barbear", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Higiene") , 'valor' : 12},
    {'descricao' :  "Pente Fino", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Higiene") , 'valor' : 4},
    {'descricao' :  "Hastes Flexiveis com Ponta de Algodao", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Higiene") , 'valor' : 3.20},
    {'descricao' :  "Teclado", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Informatica") , 'valor' : 30},
    {'descricao' :  "Monitor 24 polegadas", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Informatica") , 'valor' : 1100},
    {'descricao' :  "Caixa de Som", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Informatica") , 'valor' : 35},
    {'descricao' :  "Computador i7", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Informatica") , 'valor' : 3089.50},
    {'descricao' :  "Mouse", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Informatica") , 'valor' : 15.60},
    {'descricao' :  "Pão unidade", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Padaria") , 'valor' : 0.80},
    {'descricao' :  "Bolo", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Padaria") , 'valor' : 15},
    {'descricao' :  "Pastel", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Padaria") , 'valor' : 5.50},
    {'descricao' :  "Torta de Frango", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Padaria") , 'valor' : 80},
    {'descricao' :  "Pudim", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Padaria") , 'valor' : 50},
    {'descricao' :  "Cerveja skol 350 ml", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Bebidas") , 'valor' : 3.80},
    {'descricao' :  "Agua Mineral 500 ml", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Bebidas") , 'valor' : 2},
    {'descricao' :  "Whisky 1000 ml", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Bebidas") , 'valor' : 145},
    {'descricao' :  "Suco de Uva 500 ml", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Bebidas") , 'valor' : 4.50},
    {'descricao' :  "Agua Tonica 350 ml", 'id_categoria' : CATEGORIA.select(id).where(CATEGORIA.descricao == "Bebidas") , 'valor' : 6}
]

PRODUTOS.insert_many(produtos).execute()

historico_precos = [
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Folha A4 - 500 unidades")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Tesoura"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Tesoura")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Grampeador"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Grampeador")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Regua 30cm"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Regua 30cm")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Papel Higienico 16 unidade")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Creme Dental"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Creme Dental")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Lamina de Barbear"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Lamina de Barbear")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pente Fino"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pente Fino")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Teclado"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Teclado")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Monitor 24 polegadas")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caixa de Som"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caixa de Som")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Computador i7"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Computador i7")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Mouse"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Mouse")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pão unidade"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pão unidade")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Bolo"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Bolo")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pastel"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pastel")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Torta de Frango"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Torta de Frango")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pudim"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pudim")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Cerveja skol 350 ml")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Mineral 500 ml")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Whisky 1000 ml")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Suco de Uva 500 ml")},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'valor' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Tonica 350 ml")}
]

HISTORICO_PRECOS.insert_many(historico_precos).execute()

vendas = [
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 5 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 6 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Tesoura"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 3 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Tesoura"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Grampeador"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 8 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Grampeador"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Regua 30cm"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 45 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Regua 30cm"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 7 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Creme Dental"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 12 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Creme Dental"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Lamina de Barbear"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 76 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Lamina de Barbear"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pente Fino"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 234 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pente Fino"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 87 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Teclado"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 987 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Teclado"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 90 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caixa de Som"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 34 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caixa de Som"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Computador i7"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 67 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Computador i7"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Mouse"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 1234 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Mouse"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pão unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 60 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pão unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Bolo"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 123 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Bolo"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pastel"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 367 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pastel"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Torta de Frango"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 980 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Torta de Frango"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pudim"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 23 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pudim"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 43 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 21 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 12 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 5 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Edgler Martins") , 'quantidade' : 3 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 15 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 56 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Tesoura"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 53 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Tesoura"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Grampeador"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 18 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Grampeador"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Regua 30cm"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 5 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Regua 30cm"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 7 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Creme Dental"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 2 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Creme Dental"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Lamina de Barbear"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 6 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Lamina de Barbear"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pente Fino"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 24 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pente Fino"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 7 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Teclado"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 97 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Teclado"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 970 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caixa de Som"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 314 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caixa de Som"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Computador i7"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 617 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Computador i7"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Mouse"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 124 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Mouse"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pão unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 610 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pão unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Bolo"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 13 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Bolo"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pastel"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 37 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pastel"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Torta de Frango"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 80 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Torta de Frango"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pudim"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 213 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pudim"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 413 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 241 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 152 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 51 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Helder Martins") , 'quantidade' : 31 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},

    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 115 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 6 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Tesoura"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 5 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Tesoura"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Grampeador"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 148 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Grampeador"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Regua 30cm"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 5 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Regua 30cm"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 74 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Creme Dental"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 2 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Creme Dental"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Lamina de Barbear"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 61 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Lamina de Barbear"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pente Fino"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 24 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pente Fino"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 7 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Teclado"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 97 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Teclado"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 9470 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caixa de Som"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 314 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caixa de Som"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Computador i7"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 6117 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Computador i7"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Mouse"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 124 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Mouse"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pão unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 610 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pão unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Bolo"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 13 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Bolo"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pastel"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 7 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pastel"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Torta de Frango"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 80 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Torta de Frango"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pudim"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 13 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pudim"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 43 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 24 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 12 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 1 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Maria dos Remedios") , 'quantidade' : 341 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},

    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 15 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caneta Bic esferográfica azul"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 61 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Folha A4 - 500 unidades"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Tesoura"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 15 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Tesoura"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Grampeador"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 18 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Grampeador"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Regua 30cm"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 15 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Regua 30cm"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 74 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Papel Higienico 16 unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Creme Dental"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 12 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Creme Dental"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Lamina de Barbear"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 1 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Lamina de Barbear"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pente Fino"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 2 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pente Fino"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 7 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Teclado"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Eveline Martins") , 'quantidade' : 7 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Teclado"), 'valor_total' : 'quantidade' * 'valor_unitario'},

    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 17 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Hastes Flexiveis com Ponta de Algodao"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Teclado"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 9 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Teclado"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 940 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Monitor 24 polegadas"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Caixa de Som"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 34 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Caixa de Som"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Computador i7"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 67 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Computador i7"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Mouse"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 124 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Mouse"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pão unidade"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 610 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pão unidade"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Bolo"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 13 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Bolo"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pastel"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 71 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pastel"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Torta de Frango"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 8 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Torta de Frango"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Pudim"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 113 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Pudim"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 413 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Cerveja skol 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 214 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Mineral 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 112 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Whisky 1000 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 11 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Suco de Uva 500 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'},
    {'id_produto' : PRODUTOS.select(id).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'id_cliente' : CLIENTE.select(id).where(CLIENTE.nome == "Paulo Martins") , 'quantidade' : 31 , 'valor_unitario' : PRODUTOS.select(valor).where(PRODUTOS.descricao == "Agua Tonica 350 ml"), 'valor_total' : 'quantidade' * 'valor_unitario'}
]

CATEGORIA.insert_many(categorias).execute()
